name: UbH-GCN
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - python=3.9
  - pytorch-cuda=11.8
  - pyyaml
  - matplotlib
  - einops
  - scikit-learn
  - tqdm
  - h5py
  - pip:
      - torchpack == 0.2.2
      - tensorboardx